# This workflow will install Python dependencies, build the documentation using Sphinx, and add the docs to the documentation directory.
# Based on python actions template: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Sphinx build and deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade -r requirements.txt
    - name: Build Sphinx for Github Pages
      run: |
        rm -rf ./docs
        python -m sphinx source docs
    - name: Create README.md
      run: |
        cat ./source/about/about.md >> README.md
        echo "\n#" -n >> README.md
        cat ./source/about/contributing.md >> README.md
    - name: Create .nojekyll
      run: |
        touch ./docs/.nojekyll    
